// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ViveDB {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    
    
    [UnityEditor.InitializeOnLoadAttribute()]
    [uFrame.Attributes.uFrameIdentifier("81a19d81-7bd1-4ced-b9dc-546a180366fc")]
    public class ViveDBEditorExtensions {
        
        [UnityEditor.MenuItem("GameObject/Create ViveDB Kernel", false, 0)]
        public static void AddKernel() {
            uFrame.ECS.Templates.EcsEditorExtensionTemplate.AddEcsKernelWith<ViveDB.ViveDBLoader>();
        }
    }
}
