// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ViveDB {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.Components;
    using uFrame.Json;
    using UniRx;
    using UnityEngine;
    
    
    [uFrame.Attributes.ComponentId(11)]
    [uFrame.Attributes.uFrameIdentifier("14bceec3-46c7-4d32-9bfa-f7aa9ea57c47")]
    public partial class Bullet : uFrame.ECS.Components.EcsComponent {
        
        public override int ComponentId {
            get {
                return 11;
            }
        }
    }
}
