// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ViveDB {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.Components;
    using uFrame.Json;
    using UniRx;
    using UnityEngine;
    
    
    [uFrame.Attributes.ComponentId(12)]
    [uFrame.Attributes.uFrameIdentifier("cf74afdb-92dd-4520-8915-0daf84d86cce")]
    public partial class Checkpoint : uFrame.ECS.Components.EcsComponent {
        
        public override int ComponentId {
            get {
                return 12;
            }
        }
    }
}
