// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ViveDB {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.Components;
    using uFrame.Json;
    using UniRx;
    using UnityEngine;
    
    
    [uFrame.Attributes.ComponentId(14)]
    [uFrame.Attributes.uFrameIdentifier("bd5071fe-20b5-44fe-9549-863c89654140")]
    public partial class Feet : uFrame.ECS.Components.EcsComponent {
        
        public override int ComponentId {
            get {
                return 14;
            }
        }
    }
}
