// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ViveDB {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.Components;
    using uFrame.Json;
    using UniRx;
    using UnityEngine;
    
    
    [uFrame.Attributes.ComponentId(9)]
    [uFrame.Attributes.uFrameIdentifier("1ea2c13c-6db3-42e0-8824-71085035e969")]
    public partial class Rig : uFrame.ECS.Components.EcsComponent {
        
        public override int ComponentId {
            get {
                return 9;
            }
        }
    }
}
