// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ViveDB {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.Components;
    using uFrame.Json;
    using UniRx;
    using UnityEngine;
    
    
    [uFrame.Attributes.ComponentId(4)]
    [uFrame.Attributes.uFrameIdentifier("f6164f45-d104-4ff7-a0ea-1224d748d3d8")]
    public partial class Wand : uFrame.ECS.Components.EcsComponent {
        
        public override int ComponentId {
            get {
                return 4;
            }
        }
    }
}
