// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ViveDB {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    using UniRx;
    
    
    [uFrame.Attributes.ComponentId(1)]
    public partial class Wands : uFrame.ECS.Components.GroupItem {
        
        private WandLeft _WandLeft;
        
        private WandRight _WandRight;
        
        public WandLeft WandLeft {
            get {
                return _WandLeft;
            }
            set {
                _WandLeft = value;
            }
        }
        
        public WandRight WandRight {
            get {
                return _WandRight;
            }
            set {
                _WandRight = value;
            }
        }
        
        public override int ComponentId {
            get {
                return 1;
            }
        }
    }
}
