// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ViveDB {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using UniRx;
    using UnityEngine;
    using ViveDB;
    
    
    [uFrame.Attributes.EventId(2)]
    public partial class PlayerMoveEvent : object {
        
        [UnityEngine.SerializeField()]
        private Vector2 _movement;
        
        public Vector2 movement {
            get {
                return _movement;
            }
            set {
                _movement = value;
            }
        }
    }
}
