// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ViveDB {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS.APIs;
    using uFrame.ECS.Components;
    using uFrame.ECS.Systems;
    using uFrame.Kernel;
    using UniRx;
    using UnityEngine;
    using ViveDB;
    
    
    public partial class PlayerSystemBase : uFrame.ECS.Systems.EcsSystem {
        
        private IEcsComponentManagerOf<WandManager> _WandManagerManager;
        
        private IEcsComponentManagerOf<Player> _PlayerManager;
        
        private IEcsComponentManagerOf<Grabable> _GrabableManager;
        
        private IEcsComponentManagerOf<WandRight> _WandRightManager;
        
        private IEcsComponentManagerOf<Turret> _TurretManager;
        
        private IEcsComponentManagerOf<Feet> _FeetManager;
        
        private IEcsComponentManagerOf<Checkpoint> _CheckpointManager;
        
        private IEcsComponentManagerOf<Menu> _MenuManager;
        
        private IEcsComponentManagerOf<Bullet> _BulletManager;
        
        private IEcsComponentManagerOf<WandLeft> _WandLeftManager;
        
        private IEcsComponentManagerOf<Rig> _RigManager;
        
        public IEcsComponentManagerOf<WandManager> WandManagerManager {
            get {
                return _WandManagerManager;
            }
            set {
                _WandManagerManager = value;
            }
        }
        
        public IEcsComponentManagerOf<Player> PlayerManager {
            get {
                return _PlayerManager;
            }
            set {
                _PlayerManager = value;
            }
        }
        
        public IEcsComponentManagerOf<Grabable> GrabableManager {
            get {
                return _GrabableManager;
            }
            set {
                _GrabableManager = value;
            }
        }
        
        public IEcsComponentManagerOf<WandRight> WandRightManager {
            get {
                return _WandRightManager;
            }
            set {
                _WandRightManager = value;
            }
        }
        
        public IEcsComponentManagerOf<Turret> TurretManager {
            get {
                return _TurretManager;
            }
            set {
                _TurretManager = value;
            }
        }
        
        public IEcsComponentManagerOf<Feet> FeetManager {
            get {
                return _FeetManager;
            }
            set {
                _FeetManager = value;
            }
        }
        
        public IEcsComponentManagerOf<Checkpoint> CheckpointManager {
            get {
                return _CheckpointManager;
            }
            set {
                _CheckpointManager = value;
            }
        }
        
        public IEcsComponentManagerOf<Menu> MenuManager {
            get {
                return _MenuManager;
            }
            set {
                _MenuManager = value;
            }
        }
        
        public IEcsComponentManagerOf<Bullet> BulletManager {
            get {
                return _BulletManager;
            }
            set {
                _BulletManager = value;
            }
        }
        
        public IEcsComponentManagerOf<WandLeft> WandLeftManager {
            get {
                return _WandLeftManager;
            }
            set {
                _WandLeftManager = value;
            }
        }
        
        public IEcsComponentManagerOf<Rig> RigManager {
            get {
                return _RigManager;
            }
            set {
                _RigManager = value;
            }
        }
        
        public override void Setup() {
            base.Setup();
            WandManagerManager = ComponentSystem.RegisterComponent<WandManager>(5);
            PlayerManager = ComponentSystem.RegisterComponent<Player>(6);
            GrabableManager = ComponentSystem.RegisterComponent<Grabable>(7);
            WandRightManager = ComponentSystem.RegisterComponent<WandRight>(1);
            TurretManager = ComponentSystem.RegisterComponent<Turret>(10);
            FeetManager = ComponentSystem.RegisterComponent<Feet>(14);
            CheckpointManager = ComponentSystem.RegisterComponent<Checkpoint>(12);
            MenuManager = ComponentSystem.RegisterComponent<Menu>(13);
            BulletManager = ComponentSystem.RegisterComponent<Bullet>(11);
            WandLeftManager = ComponentSystem.RegisterComponent<WandLeft>(3);
            RigManager = ComponentSystem.RegisterComponent<Rig>(9);
            this.OnEvent<ViveDB.JumpEvent>().Subscribe(_=>{ PlayerSystemJumpEventFilter(_); }).DisposeWith(this);
            this.OnEvent<ViveDB.PlayerMoveEvent>().Subscribe(_=>{ PlayerSystemPlayerMoveEventFilter(_); }).DisposeWith(this);
            this.OnEvent<uFrame.ECS.UnityUtilities.OnCollisionEnterDispatcher>().Subscribe(_=>{ PlayerSystemOnCollisionEnterFilter(_); }).DisposeWith(this);
            this.OnEvent<uFrame.ECS.UnityUtilities.OnTriggerEnterDispatcher>().Subscribe(_=>{ PlayerSystemFeetOnTriggerEnterFilter(_); }).DisposeWith(this);
            this.OnEvent<uFrame.ECS.UnityUtilities.OnTriggerEnterDispatcher>().Subscribe(_=>{ PlayerSystemOnTriggerEnterFilter(_); }).DisposeWith(this);
            this.OnEvent<ViveDB.DeathEvent>().Subscribe(_=>{ PlayerSystemDeathEventFilter(_); }).DisposeWith(this);
        }
        
        protected virtual void PlayerSystemJumpEventHandler(ViveDB.JumpEvent data, Player group) {
        }
        
        protected void PlayerSystemJumpEventFilter(ViveDB.JumpEvent data) {
            var PlayerItems = PlayerManager.Components;
            for (var PlayerIndex = 0
            ; PlayerIndex < PlayerItems.Count; PlayerIndex++
            ) {
                if (!PlayerItems[PlayerIndex].Enabled) {
                    continue;
                }
                this.PlayerSystemJumpEventHandler(data, PlayerItems[PlayerIndex]);
            }
        }
        
        protected virtual void PlayerSystemPlayerMoveEventHandler(ViveDB.PlayerMoveEvent data, Player group) {
        }
        
        protected void PlayerSystemPlayerMoveEventFilter(ViveDB.PlayerMoveEvent data) {
            var PlayerItems = PlayerManager.Components;
            for (var PlayerIndex = 0
            ; PlayerIndex < PlayerItems.Count; PlayerIndex++
            ) {
                if (!PlayerItems[PlayerIndex].Enabled) {
                    continue;
                }
                this.PlayerSystemPlayerMoveEventHandler(data, PlayerItems[PlayerIndex]);
            }
        }
        
        protected virtual void PlayerSystemOnCollisionEnterHandler(uFrame.ECS.UnityUtilities.OnCollisionEnterDispatcher data, Bullet collider, Player source) {
        }
        
        protected void PlayerSystemOnCollisionEnterFilter(uFrame.ECS.UnityUtilities.OnCollisionEnterDispatcher data) {
            var ColliderBullet = BulletManager[data.ColliderId];
            if (ColliderBullet == null) {
                return;
            }
            if (!ColliderBullet.Enabled) {
                return;
            }
            var SourcePlayer = PlayerManager[data.EntityId];
            if (SourcePlayer == null) {
                return;
            }
            if (!SourcePlayer.Enabled) {
                return;
            }
            this.PlayerSystemOnCollisionEnterHandler(data, ColliderBullet, SourcePlayer);
        }
        
        protected virtual void PlayerSystemFeetOnTriggerEnterHandler(uFrame.ECS.UnityUtilities.OnTriggerEnterDispatcher data, Feet source) {
        }
        
        protected void PlayerSystemFeetOnTriggerEnterFilter(uFrame.ECS.UnityUtilities.OnTriggerEnterDispatcher data) {
            var SourceFeet = FeetManager[data.EntityId];
            if (SourceFeet == null) {
                return;
            }
            if (!SourceFeet.Enabled) {
                return;
            }
            this.PlayerSystemFeetOnTriggerEnterHandler(data, SourceFeet);
        }
        
        protected virtual void PlayerSystemOnTriggerEnterHandler(uFrame.ECS.UnityUtilities.OnTriggerEnterDispatcher data, Checkpoint collider, Player source) {
        }
        
        protected void PlayerSystemOnTriggerEnterFilter(uFrame.ECS.UnityUtilities.OnTriggerEnterDispatcher data) {
            var ColliderCheckpoint = CheckpointManager[data.ColliderId];
            if (ColliderCheckpoint == null) {
                return;
            }
            if (!ColliderCheckpoint.Enabled) {
                return;
            }
            var SourcePlayer = PlayerManager[data.EntityId];
            if (SourcePlayer == null) {
                return;
            }
            if (!SourcePlayer.Enabled) {
                return;
            }
            this.PlayerSystemOnTriggerEnterHandler(data, ColliderCheckpoint, SourcePlayer);
        }
        
        protected virtual void PlayerSystemDeathEventHandler(ViveDB.DeathEvent data, Player group) {
        }
        
        protected void PlayerSystemDeathEventFilter(ViveDB.DeathEvent data) {
            var PlayerItems = PlayerManager.Components;
            for (var PlayerIndex = 0
            ; PlayerIndex < PlayerItems.Count; PlayerIndex++
            ) {
                if (!PlayerItems[PlayerIndex].Enabled) {
                    continue;
                }
                this.PlayerSystemDeathEventHandler(data, PlayerItems[PlayerIndex]);
            }
        }
    }
    
    [uFrame.Attributes.uFrameIdentifier("d549aa45-7425-4a1b-af59-82c8d6e66a22")]
    public partial class PlayerSystem : PlayerSystemBase {
        
        private static PlayerSystem _Instance;
        
        public PlayerSystem() {
            Instance = this;
        }
        
        public static PlayerSystem Instance {
            get {
                return _Instance;
            }
            set {
                _Instance = value;
            }
        }
    }
}
