// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ViveDB {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.UnityUtilities;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class PlayerSystemUpdateHandler {
        
        public Player Group;
        
        private uFrame.ECS.APIs.ISystemUpdate _Event;
        
        private uFrame.ECS.Systems.EcsSystem _System;
        
        private UnityEngine.KeyCode ActionNode30_key = default( UnityEngine.KeyCode );
        
        private bool ActionNode30_Result = default( System.Boolean );
        
        private object ActionNode31_message = default( System.Object );
        
        private string StringNode32 = "Jump";
        
        private ViveDB.JumpEvent PublishEventNode26_Result = default( ViveDB.JumpEvent );
        
        public uFrame.ECS.APIs.ISystemUpdate Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.Systems.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            ActionNode30_key = Group.space;
            // ActionNode
            while (this.DebugInfo("","6d4c4f28-f49c-438d-88c3-be7a8b86388e", this) == 1) yield return null;
            // Visit uFrame.ECS.Actions.InputLibrary.IsKeyDown
            ActionNode30_Result = uFrame.ECS.Actions.InputLibrary.IsKeyDown(ActionNode30_key, ()=> { System.StartCoroutine(ActionNode30_yes()); }, ()=> { System.StartCoroutine(ActionNode30_no()); });
            yield break;
        }
        
        private System.Collections.IEnumerator ActionNode30_yes() {
            ActionNode31_message = StringNode32;
            // ActionNode
            while (this.DebugInfo("6d4c4f28-f49c-438d-88c3-be7a8b86388e","226d85ad-7318-4bc1-8651-7fce3ebbb219", this) == 1) yield return null;
            // Visit uFrame.ECS.Actions.DebugLibrary.LogMessage
            uFrame.ECS.Actions.DebugLibrary.LogMessage(ActionNode31_message);
            // PublishEventNode
            while (this.DebugInfo("226d85ad-7318-4bc1-8651-7fce3ebbb219","62df12b9-9370-4166-ba53-98260eaf6214", this) == 1) yield return null;
            var PublishEventNode26_Event = new JumpEvent();
            System.Publish(PublishEventNode26_Event);
            PublishEventNode26_Result = PublishEventNode26_Event;
            yield break;
        }
        
        private System.Collections.IEnumerator ActionNode30_no() {
            yield break;
        }
    }
}
